import type { ApiKeySummary, ProviderConfig } from "./types";

export const mockProviders: ProviderConfig[] = [
  {
    id: "openai",
    name: "OpenAI",
    baseUrl: "https://api.openai.com/v1",
    keyFormatPattern: "^sk-[a-zA-Z0-9]+$",
    models: ["gpt-4o", "gpt-4o-mini", "gpt-4-turbo", "o1-preview", "o1-mini"],
    isBuiltIn: true,
  },
  {
    id: "anthropic",
    name: "Anthropic",
    baseUrl: "https://api.anthropic.com/v1",
    keyFormatPattern: "^sk-ant-[a-zA-Z0-9-]+$",
    models: ["claude-sonnet-4-20250514", "claude-3-5-haiku-20241022"],
    isBuiltIn: true,
  },
  {
    id: "google",
    name: "Google AI",
    baseUrl: "https://generativelanguage.googleapis.com/v1beta",
    keyFormatPattern: "^AIza[a-zA-Z0-9_-]+$",
    models: ["gemini-2.0-flash", "gemini-1.5-pro", "gemini-1.5-flash"],
    isBuiltIn: true,
  },
  {
    id: "zhipu",
    name: "智谱 AI",
    baseUrl: "https://open.bigmodel.cn/api/paas/v4",
    keyFormatPattern: "^[a-f0-9.]+$",
    models: ["glm-4-plus", "glm-4-air", "glm-4-flash"],
    isBuiltIn: true,
  },
  {
    id: "qwen",
    name: "通义千问",
    baseUrl: "https://dashscope.aliyuncs.com/compatible-mode/v1",
    keyFormatPattern: "^sk-[a-f0-9]+$",
    models: ["qwen-max", "qwen-plus", "qwen-turbo"],
    isBuiltIn: true,
  },
  {
    id: "deepseek",
    name: "DeepSeek",
    baseUrl: "https://api.deepseek.com/v1",
    keyFormatPattern: "^sk-[a-zA-Z0-9]+$",
    models: ["deepseek-chat", "deepseek-reasoner"],
    isBuiltIn: true,
  },
  {
    id: "moonshot",
    name: "Kimi（月之暗面）",
    baseUrl: "https://api.moonshot.cn/v1",
    keyFormatPattern: "^sk-[a-zA-Z0-9_-]+$",
    models: ["kimi-latest", "moonshot-v1-8k", "moonshot-v1-32k"],
    isBuiltIn: true,
  },
  {
    id: "openrouter",
    name: "OpenRouter",
    baseUrl: "https://openrouter.ai/api/v1",
    keyFormatPattern: "^sk-or-[a-zA-Z0-9_-]+$",
    models: ["openai/gpt-4o", "anthropic/claude-sonnet-4", "deepseek/deepseek-chat"],
    isBuiltIn: true,
  },
  {
    id: "siliconflow",
    name: "硅基流动 SiliconFlow",
    baseUrl: "https://api.siliconflow.cn/v1",
    keyFormatPattern: "^sk-[a-zA-Z0-9_-]+$",
    models: ["deepseek-ai/DeepSeek-V3", "Qwen/Qwen2.5-72B-Instruct"],
    isBuiltIn: true,
  },
];

export const mockApiKeys: ApiKeySummary[] = [
  {
    id: "key-1",
    name: "OpenAI 主力 Key",
    providerId: "openai",
    providerName: "OpenAI",
    tags: ["生产", "GPT-4"],
    createdAt: "2026-01-15T08:00:00Z",
    updatedAt: "2026-09-10T14:30:00Z",
    lastUsedAt: "2026-09-17T09:15:00Z",
  },
  {
    id: "key-2",
    name: "Claude 开发测试",
    providerId: "anthropic",
    providerName: "Anthropic",
    tags: ["开发", "测试"],
    createdAt: "2026-03-20T10:00:00Z",
    updatedAt: "2026-09-15T16:00:00Z",
    lastUsedAt: "2026-09-17T08:45:00Z",
  },
  {
    id: "key-3",
    name: "Gemini 实验 Key",
    providerId: "google",
    providerName: "Google AI",
    tags: ["实验"],
    createdAt: "2026-05-01T12:00:00Z",
    updatedAt: "2026-08-20T11:00:00Z",
    lastUsedAt: "2026-09-16T17:30:00Z",
  },
  {
    id: "key-4",
    name: "智谱 GLM-4 生产",
    providerId: "zhipu",
    providerName: "智谱 AI",
    tags: ["生产", "中文"],
    createdAt: "2026-02-10T09:00:00Z",
    updatedAt: "2026-09-12T10:00:00Z",
    lastUsedAt: "2026-09-17T07:00:00Z",
  },
  {
    id: "key-5",
    name: "通义千问 备用",
    providerId: "qwen",
    providerName: "通义千问",
    tags: ["备用"],
    createdAt: "2026-04-05T14:00:00Z",
    updatedAt: "2026-09-01T09:00:00Z",
    lastUsedAt: "2026-09-14T12:00:00Z",
  },
  {
    id: "key-6",
    name: "OpenAI 备用 Key",
    providerId: "openai",
    providerName: "OpenAI",
    tags: ["备用"],
    createdAt: "2026-06-15T08:00:00Z",
    updatedAt: "2026-09-05T15:00:00Z",
    lastUsedAt: null,
  },
  {
    id: "key-7",
    name: "Claude 生产 Key",
    providerId: "anthropic",
    providerName: "Anthropic",
    tags: ["生产"],
    createdAt: "2026-07-01T10:00:00Z",
    updatedAt: "2026-09-16T08:00:00Z",
    lastUsedAt: "2026-09-17T10:00:00Z",
  },
  {
    id: "key-8",
    name: "智谱 测试专用",
    providerId: "zhipu",
    providerName: "智谱 AI",
    tags: ["测试"],
    createdAt: "2026-08-20T11:00:00Z",
    updatedAt: "2026-09-10T14:00:00Z",
    lastUsedAt: "2026-09-15T16:30:00Z",
  },
];
